import SEO from '../components/SEO';
import PageLayout from '../components/PageLayout';

const PATH = '/understanding-spring-webflux-project-structure-and-key-files';

export default function UnderstandingProjectStructure() {
  return (
    <>
      <SEO
        title="Understanding Spring WebFlux Project Structure and Key Files"
        description="Explore every folder and file in a Spring WebFlux project: main class, application.yml, package conventions, and how the auto-configuration wires everything together."
        path={PATH}
        keywords="Spring WebFlux project structure, application.yml, Spring Boot packages, auto-configuration"
      />
      <PageLayout
        breadcrumb="Getting Started"
        title="Understanding Spring WebFlux Project Structure and Key Files"
        description="A thorough tour of every folder and file generated by Spring Initializr — what each one does, the package naming conventions to follow, and how Spring Boot auto-configuration binds everything together."
        badge={{ text: 'Beginner', level: 'beginner' }}
        readTime="14 min read"
        currentPath={PATH}
      >
        <div className="toc">
          <div className="toc-title">On this page</div>
          <ol>
            <li><a href="#dir-tree">Directory Tree</a></li>
            <li><a href="#main-class">The Main Application Class</a></li>
            <li><a href="#app-yml">application.yml / application.properties</a></li>
            <li><a href="#package-layout">Recommended Package Layout</a></li>
            <li><a href="#autoconfiguration">How Auto-Configuration Works</a></li>
            <li><a href="#test-folder">The Test Folder</a></li>
          </ol>
        </div>

        <div className="section" id="dir-tree">
          <h2 className="section-title">Directory Tree</h2>
          <div className="code-block">
            <div className="code-block-header">
              <span className="code-block-lang">text</span>
              <span className="code-block-filename">project layout</span>
            </div>
            <pre><code>{`webflux-demo/
├── src/
│   ├── main/
│   │   ├── java/
│   │   │   └── com/example/webfluxdemo/
│   │   │       ├── WebfluxDemoApplication.java   ← entry point
│   │   │       ├── config/                        ← beans, security, CORS
│   │   │       ├── controller/                    ← @RestController classes
│   │   │       ├── handler/                       ← functional HandlerFunctions
│   │   │       ├── router/                        ← RouterFunction beans
│   │   │       ├── service/                       ← business logic
│   │   │       ├── repository/                    ← ReactiveCrudRepository
│   │   │       ├── model/                         ← domain entities
│   │   │       └── dto/                           ← request/response DTOs
│   │   └── resources/
│   │       ├── application.yml                    ← main config
│   │       ├── application-dev.yml                ← dev profile overrides
│   │       └── static/                            ← served as-is (optional)
│   └── test/
│       └── java/
│           └── com/example/webfluxdemo/
│               ├── WebfluxDemoApplicationTests.java
│               ├── controller/                    ← WebTestClient tests
│               └── service/                       ← StepVerifier unit tests
├── pom.xml
├── .gitignore
├── mvnw / mvnw.cmd                                ← Maven wrapper
└── HELP.md`}</code></pre>
          </div>
        </div>

        <div className="section" id="main-class">
          <h2 className="section-title">The Main Application Class</h2>
          <div className="step-content">
            <p>The <code>@SpringBootApplication</code> annotation is a convenience annotation that combines three annotations:</p>
            <ul>
              <li><code>@Configuration</code> – marks the class as a source of bean definitions.</li>
              <li><code>@EnableAutoConfiguration</code> – tells Spring Boot to start adding beans based on classpath settings, other beans, and property settings.</li>
              <li><code>@ComponentScan</code> – tells Spring to scan the current package and sub-packages for components, configurations, and services.</li>
            </ul>
            <p>Because <code>spring-boot-starter-webflux</code> is on the classpath and there is no <code>spring-boot-starter-web</code> (the blocking/Tomcat starter), Spring Boot automatically configures a Netty server.</p>
          </div>
          <div className="info-box warning">
            <span className="info-box-icon">⚠️</span>
            <div className="info-box-content">
              <div className="info-box-title">Do NOT add spring-boot-starter-web</div>
              If both <code>spring-boot-starter-web</code> and <code>spring-boot-starter-webflux</code> are on the classpath, Spring Boot will default to the Servlet (MVC) stack. WebFlux will still work but you lose the non-blocking benefits. Keep them separate.
            </div>
          </div>
        </div>

        <div className="section" id="app-yml">
          <h2 className="section-title">application.yml — Key Configuration Properties</h2>
          <div className="code-block">
            <div className="code-block-header">
              <span className="code-block-lang">yaml</span>
              <span className="code-block-filename">src/main/resources/application.yml</span>
            </div>
            <pre><code>{`spring:
  application:
    name: webflux-demo

  # R2DBC datasource (reactive, non-blocking database driver)
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mydb
    username: \${DB_USER:postgres}
    password: \${DB_PASS:secret}

  # WebFlux-specific settings
  webflux:
    base-path: /api            # global prefix for all routes (optional)
    multipart:
      max-request-size: 10MB   # maximum upload size

# Server settings
server:
  port: 8080
  # Netty-specific tuning
  netty:
    connection-timeout: 10s
    idle-timeout: 60s

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    root: INFO
    com.example.webfluxdemo: DEBUG
    reactor.netty: WARN`}</code></pre>
          </div>
        </div>

        <div className="section" id="package-layout">
          <h2 className="section-title">Recommended Package Layout</h2>
          <div className="step-content">
            <p>Organise code by <strong>technical layer</strong> (small projects) or by <strong>feature/domain</strong> (larger projects). The layer-based layout is shown in the directory tree above. Here is an example domain-based layout:</p>
          </div>
          <div className="code-block">
            <div className="code-block-header">
              <span className="code-block-lang">text</span>
              <span className="code-block-filename">domain-based layout</span>
            </div>
            <pre><code>{`com.example.webfluxdemo/
├── product/
│   ├── ProductController.java
│   ├── ProductService.java
│   ├── ProductRepository.java
│   ├── Product.java          ← entity
│   └── ProductDto.java       ← request/response DTO
├── order/
│   ├── OrderController.java
│   └── ...
└── shared/
    ├── config/
    └── exception/`}</code></pre>
          </div>
          <div className="info-box tip">
            <span className="info-box-icon">💡</span>
            <div className="info-box-content">
              <div className="info-box-title">Prefer domain-based layout for microservices</div>
              It makes it easier to extract a domain into its own microservice later. The layer-based layout is fine for small projects and learning exercises.
            </div>
          </div>
        </div>

        <div className="section" id="autoconfiguration">
          <h2 className="section-title">How Auto-Configuration Works</h2>
          <div className="step-content">
            <p>Spring Boot scans <code>META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports</code> files inside every jar on the classpath. Each entry is a <code>@Configuration</code> class guarded by <code>@ConditionalOn*</code> annotations.</p>
            <p>For WebFlux, the key auto-configurations are:</p>
            <ul>
              <li><code>ReactiveWebServerFactoryAutoConfiguration</code> – creates the Netty server.</li>
              <li><code>WebFluxAutoConfiguration</code> – sets up the DispatcherHandler, codecs, CORS, and exception handling.</li>
              <li><code>R2dbcAutoConfiguration</code> – creates the <code>ConnectionFactory</code> bean.</li>
              <li><code>R2dbcRepositoriesAutoConfiguration</code> – scans for <code>ReactiveCrudRepository</code> interfaces.</li>
            </ul>
          </div>
        </div>

        <div className="section" id="test-folder">
          <h2 className="section-title">The Test Folder</h2>
          <div className="step-content">
            <p>Spring Boot ships two powerful testing utilities for reactive apps:</p>
            <ul>
              <li><code>WebTestClient</code> – a non-blocking, fluent HTTP client for integration-testing controllers end-to-end.</li>
              <li><code>StepVerifier</code> (from <code>reactor-test</code>) – for unit-testing Mono/Flux pipelines step by step.</li>
            </ul>
          </div>
          <div className="code-block">
            <div className="code-block-header">
              <span className="code-block-lang">java</span>
              <span className="code-block-filename">WebfluxDemoApplicationTests.java</span>
            </div>
            <pre><code>{`@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class WebfluxDemoApplicationTests {

    @Autowired
    private WebTestClient webTestClient;

    @Test
    void contextLoads() {
        webTestClient.get()
            .uri("/hello")
            .exchange()
            .expectStatus().isOk()
            .expectBody(String.class)
            .isEqualTo("Hello, World! Welcome to Spring WebFlux.");
    }
}`}</code></pre>
          </div>
          <div className="info-box success">
            <span className="info-box-icon">✅</span>
            <div className="info-box-content">
              <div className="info-box-title">Project structure understood!</div>
              Now let's dive into the core reactive types — <code>Mono</code> and <code>Flux</code> — that underpin everything in Spring WebFlux.
            </div>
          </div>
        </div>
      </PageLayout>
    </>
  );
}
